name: Dynamic Environment Deployment

run-name: Deploy ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: string
      app_version_id:
        description: 'The app version id'
        required: true
        type: string
      app_id:
        description: 'The app version id'
        required: true
        type: string

concurrency:
  group: deploy-${{ github.event.inputs.environment }}
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Example Step
        run: echo "Deploying ${{ inputs.environment }} environment"
      - name: Sleep 5 minutes
        run: sleep 300
      - name: The End
        run: echo "Ended"
