name: Deploy (PRD)

run-name: Deploy ${{ github.event.inputs.app }} (PRD)

on:
  workflow_dispatch:
    inputs:
      app:
        description: 'App to deploy'
        required: true
        type: string
      app_version_id:
        description: 'The app version id'
        required: true
        type: string
      app_id:
        description: 'The app version id'
        required: true
        type: string

concurrency:
  group: deploy-${{ github.event.inputs.app }}-prd
  cancel-in-progress: false

jobs:
  deploy-canada:
    name: 🚀 Deploy to td-ca-1
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.app }}
    steps:
      - name: Example Step Canada
        run: echo "Deploying ${{ inputs.app }}"
      - name: Sleep 1 minute
        run: sleep 60
      - name: The End
        run: echo "Ended"

  wait-gate-td-ca-1:
    name: 'Soak Time (td-ca-1)'
    environment: prd(td-ca-1)
    needs: deploy-canada
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Waiting...'
          
  deploy-europe:
    name: 🚀 Deploy to td-eu-1
    runs-on: ubuntu-latest
    needs: wait-gate-td-ca-1
    environment: ${{ github.event.inputs.app }}
    steps:
      - name: Example Step Europe
        run: echo "Deploying ${{ inputs.app }}"
      - name: Sleep 1 minute
        run: sleep 60
      - name: The End
        run: echo "Ended"
        
  wait-gate-td-eu-1:
    name: 'Soak Time (td-eu-1)'
    environment: prd(td-eu-1)
    needs: deploy-europe
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Waiting...'

  deploy-us:
    name: 🚀 Deploy to td-us-1
    runs-on: ubuntu-latest
    needs: wait-gate-td-eu-1
    environment: ${{ github.event.inputs.app }}
    steps:
      - name: Example Step US
        run: echo "Deploying ${{ inputs.app }}"
      - name: Sleep 1 minute
        run: sleep 60
      - name: The End
        run: echo "Ended"
        
  wait-gate-td-us-1:
    name: 'Soak Time (td-us-1)'
    environment: prd(td-us-1)
    needs: deploy-us
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Waiting...'
